# Generated by Django 3.2.3 on 2021-06-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_changing_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.IntegerField(),
        ),
    ]
